### ISSUE TITLE
`params` unavailable in Itamae::Resource::Base::EvalContext when `define`

### ISSUE THREAD

**Issue by igrep** [itamae-kitchen/itamae#225]
:memo: I updated the SSCCE to avoid error by sh
# Problem

In a definition, NameError happens when referring `params` in the resource block.

I report this as a bug because I guess this means [the sample in wiki](https://github.com/itamae-kitchen/itamae/wiki/Definitions) can't be executed.
## SSCCE

define.rb:

``` rb
puts "Ruby version: #{RUBY_VERSION}"
puts "Itamae version: #{Itamae::VERSION}"

define :foo do
  execute "bar" do
    command "echo #{params[:name]}"
  end
end

foo '"<this should be printed>"'
```

The output:

``` bash
$ itamae local define.rb
 INFO : Starting Itamae...
Ruby version: 2.1.5
Itamae version: 1.9.9
/var/lib/gems/2.1.0/gems/itamae-1.9.9/lib/itamae/resource/base.rb:40:in `method_missing': undefined local variable or method `params' for #<Itamae::Resource::Base::EvalContext:0x000000021e19d0> (NameError)
        from /home/yu/pj/itamae-bug-define-params/define.rb:6:in `block (2 levels) in load'

...
```

**Comment by igrep** [comment]
For folks who got stuck by this bug, here's a workaround:

```rb
puts "Ruby version: #{RUBY_VERSION}"
puts "Itamae version: #{Itamae::VERSION}"

define :foo do
  name = params[:name] # save params as a local variable to make available in the execute block
  execute "bar" do
    command "echo #{name}"
  end
end

foo '"<this should be printed>"'
```

**Comment by ryotarai** [comment]
Thank you for reporting. This is unintended behavior but I do not have time to fix it for now.
I just modified the sample in Wiki. Thank you again
