### ISSUE TITLE
Can't use help command

### ISSUE THREAD

**Issue by kawakubox** [itamae-kitchen/itamae#234]
Hello

I used itamae (v1.9.10).

I happened error, when I called `itamae help ssh`.

```
$ bundle exec itamae help init
bundler: failed to load command: itamae (/Users/kawakubox/Workspace/generic-recipe/vendor/bundle/ruby/2.3.0/bin/itamae)
NoMethodError: undefined method `upcase' for nil:NilClass
  /Users/kawakubox/Workspace/generic-recipe/vendor/bundle/ruby/2.3.0/gems/itamae-1.9.10/lib/itamae/cli.rb:15:in `initialize'
  /Users/kawakubox/Workspace/generic-recipe/vendor/bundle/ruby/2.3.0/gems/thor-0.19.4/lib/thor.rb:365:in `new'
  /Users/kawakubox/Workspace/generic-recipe/vendor/bundle/ruby/2.3.0/gems/thor-0.19.4/lib/thor.rb:365:in `dispatch'
  /Users/kawakubox/Workspace/generic-recipe/vendor/bundle/ruby/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /Users/kawakubox/Workspace/generic-recipe/vendor/bundle/ruby/2.3.0/gems/itamae-1.9.10/bin/itamae:4:in `<top (required)>'
  /Users/kawakubox/Workspace/generic-recipe/vendor/bundle/ruby/2.3.0/bin/itamae:22:in `load'
  /Users/kawakubox/Workspace/generic-recipe/vendor/bundle/ruby/2.3.0/bin/itamae:22:in `<top (required)>'
```

It looks like disappeared `log_level` option value.

Adding, When I changed `thor` version down to *0.19.1* , then `help` command is success!!

Is this `thor` bug??

**Comment by ryotarai** [comment]
This is fixed by https://github.com/itamae-kitchen/itamae/pull/235
