### ISSUE TITLE
Error, when help is executed

### ISSUE THREAD

**Issue by ttkit** [itamae-kitchen/itamae#237]
```
[root@localhost itamae]# ./bin/itamae help
/root/itamae/vendor/bundler/ruby/2.2.0/gems/itamae-1.9.10/lib/itamae/cli.rb:15:in `initialize': undefined method `upcase' for nil:NilClass (NoMethodError)
	from /root/itamae/vendor/bundler/ruby/2.2.0/gems/thor-0.19.4/lib/thor.rb:365:in `new'
	from /root/itamae/vendor/bundler/ruby/2.2.0/gems/thor-0.19.4/lib/thor.rb:365:in `dispatch'
	from /root/itamae/vendor/bundler/ruby/2.2.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /root/itamae/vendor/bundler/ruby/2.2.0/gems/itamae-1.9.10/bin/itamae:4:in `<top (required)>'
	from ./bin/itamae:17:in `load'
	from ./bin/itamae:17:in `<main>'
```

ruby version
```
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]
```

**Comment by ryotarai** [comment]
This is fixed by https://github.com/itamae-kitchen/itamae/pull/235
