### ISSUE TITLE
How to make it verbose?

### ISSUE THREAD

**Issue by Paxa** [itamae-kitchen/itamae#239]
when I run `itamae --help` it says:
```
/Users/pavel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/itamae-1.9.10/lib/itamae/cli.rb:15:in `initialize': undefined method `upcase' for nil:NilClass (NoMethodError)
	from /Users/pavel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:365:in `new'
	from /Users/pavel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:365:in `dispatch'
	from /Users/pavel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/pavel/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/itamae-1.9.10/bin/itamae:4:in `<top (required)>'
	from /Users/pavel/.rbenv/versions/2.3.1/bin/itamae:23:in `load'
	from /Users/pavel/.rbenv/versions/2.3.1/bin/itamae:23:in `<main>'
```

running with `-v` or `--verbose` or `--debug` didn't help

**Comment by ryotarai** [comment]
This is fixed by https://github.com/itamae-kitchen/itamae/pull/235

**Comment by Paxa** [comment]
it works, thank you!
